### ISSUE TITLE
Incompatible With Whitespace

### ISSUE THREAD

**Issue by efectn** [maoschanz/dynamic-wallpaper-editor#65] opened 2021-03-18 11:06 UTC
When we use directory path like /home/x/Backgrounds test/, it does not change the whitespaces to "\ ". That's why PATHs are set incorrectly.

**Comment by maoschanz** [comment] 2021-03-18 12:05
Sorry i don't know what you're talking about. What's your issue? When is there is a bug? What are the steps to reproduce it? Then *i* will search for the cause of the problem

**Comment by maoschanz** [comment] 2021-03-21 16:20
i have not a single problem when there are whitespaces in the names of the images, in the name of the folder containing the images, or in the name of the folder containing the xml file

so i'm closing this thread, i'll reopen it when you'll provide clear explanations about your issue

**Closed by maoschanz** 2021-03-21 16:20 UTC
