### ISSUE TITLE
[question] Simplify App Usage

### ISSUE THREAD

**Issue by aahnik** [maoschanz/dynamic-wallpaper-editor#62] opened 2020-10-07 13:15 UTC
Please take a look at this screenshot

![Screenshot from 2020-10-07 18-41-02](https://user-images.githubusercontent.com/66209958/95335245-cc5e1300-08cc-11eb-9d91-312a97828d52.png)

Here I can set the time and transition and the application figures out the start and end. 
> This picture lasts from ... to ...

How can I set the desired **start** and **end** time for each picture in a simple manner?

### It would be better if there was a start time and end time selector in hours and minutes. 

Its waste of human time and energy to write time in seconds.

What I basically want is that, to set the start time for every picture. It will last till next picture starts

Like 
Pic1 start 5 am
pic2 start 10 am
pic3 start 6 pm

and the application will figure out time in seconds and apply xml

**Comment by maoschanz** [comment] 2020-10-07 13:17
duplicate of #55

**Closed by maoschanz** 2020-10-07 13:17 UTC
Labels: duplicate

**Comment by aahnik** [comment] 2020-10-07 13:29
sorry to raise an issue so fast, before exploring the app in detail

What I actually missed was this:

![Screenshot from 2020-10-07 18-53-39](https://user-images.githubusercontent.com/66209958/95336580-77230100-08ce-11eb-8c9b-edfc89d9da38.png)

The default start hour was 6 instead of zero. 

That's why I was confused between setting the time in seconds and start times.

I was mad that the first picture was staring at 6 instead of 0, and the whole thing messed up.

My job is done . I am feeling extremely joyful now.

THANKS a lot for this tool.

setting time in seconds takes some time, but without your tool, I would have been fiddling with the XML files, which would have taken even more time.

Thanks yet again.

**Comment by aahnik** [comment] 2020-10-07 13:31
But I still believe that the app will become 100x more powerful, if it just had option to enter time in hour:minute format
