### ISSUE TITLE
Updated icon on Flathub?

### ISSUE THREAD

**Issue by foreverxml** [maoschanz/dynamic-wallpaper-editor#67] opened 2021-04-01 17:07 UTC
I was browsing through the source and it looks like there is an updated icon. Sadly, the icon is not on Flathub.
Is it possible to get the updated icon to Flathub, or not? I can't help with the compiling (never done before) but would like to just help everyone. Cheers!

**Comment by maoschanz** [comment] 2021-07-26 01:23
the last release has the new icon, but it's not on flathub because of #68 (which is a hard to solve flatpak-only bug)

i close this issue because it's a duplicate of #63

**Closed by maoschanz** 2021-07-26 01:23 UTC
Labels: duplicate, question
